USE [master]
GO
 
--select 'ALTER DATABASE [' + name + '] SET COMPATIBILITY_LEVEL = 150;' from sysdatabases 
-- where name not in ('distribution', 'master', 'model', 'msdb', 'tempdb', 'ReportServer', 'ReportServerTempDB')
-- order by 1 
 

ALTER DATABASE [ACA_Final] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [ACA_Final_Archive] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [AtlasReports] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [DataTransformations] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [MAC_EDW] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [Maintenance] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [MasterSetupAstute] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [MasterSetupStandard] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [Salesforce] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [ScanConversion] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [Sedona_Support] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [SedonaDocuments] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [SedonaMaster] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [VIVIDREPORTS-SEDONA] SET COMPATIBILITY_LEVEL = 150;

