--USE [master]
--GO
--select 'ALTER DATABASE [' + name + '] SET RECOVERY SIMPLE WITH NO_WAIT;' from sysdatabases  order by 1

ALTER DATABASE [ACA_Final] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [AtlasReports] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [Maintenance] SET RECOVERY SIMPLE WITH NO_WAIT; 
ALTER DATABASE [MasterSetupAstute] SET RECOVERY SIMPLE WITH NO_WAIT; 
ALTER DATABASE [ReportServer] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [ReportServerTempDB] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [Salesforce] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [ScanConversion] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [Sedona_Support] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [SedonaDocuments] SET RECOVERY SIMPLE WITH NO_WAIT;
ALTER DATABASE [SedonaMaster] SET RECOVERY SIMPLE WITH NO_WAIT; 
ALTER DATABASE [VIVIDREPORTS-SEDONA] SET RECOVERY SIMPLE WITH NO_WAIT;

ALTER DATABASE DataTransformations SET RECOVERY SIMPLE WITH NO_WAIT; 


